name: Release on Main 😎

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-webgl:
    name: Build project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          ## Use below variables for Professional Serial
          # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          # UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: WebGL

      # Output
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
      
      #Upload to Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/WebGL/WebGL # The folder the action should deploy.

  build-desktop:
    name: Build project ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          ## Use below variables for Professional Serial
          # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          # UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform:  ${{ matrix.targetPlatform }}
          buildName: fathomless

      - name: Fix MacOS exec
        if: matrix.targetPlatform == StandaloneOSX
        run: |
          cd build/${{ matrix.targetPlatform }}/fathomless.app/Contents/MacOS/
          chmod -R 777 fathomless

      # Output
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          allowUpdates: true
          body: "Release for LDJam #48"
          tag: "v0.1"
          artifacts: 'Build-*'
          token: ${{ secrets.GITHUB_TOKEN }}

